<a href="https://colab.research.google.com/github/gpalrepo/random_data/blob/master/prep_for_DS01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<center> <h1> Intro to Python for Data Science (NumPy and Pandas) <h1> </center> **



List of tasks to do:
Explain Data Science as a field 
The important packages and how Pandas and NumPy fit in. What unique role does each package play
Highlight what we will be building 
Explain how CoLab and Jupyter Notebooks work
Mention in email, they will need a Google Account 
Partition the different code sections and leave appropriate blanks 


In [0]:
#Importing packages 
import numpy as np 
import pandas as pd 


In [2]:
#Load dataset 

df = pd.read_csv("https://raw.githubusercontent.com/gpalrepo/inclass_practice/master/Shark%20Tank%20Companies.csv")

print(df.head())

    deal                                        description  episode  \
0  False             Bluetooth device implant for your ear.        1   
1   True  Retail and wholesale pie factory with two reta...        1   
2   True  Ava the Elephant is a godsend for frazzled par...        1   
3  False  Organizing, packing, and moving services deliv...        1   
4  False  Interactive media centers for healthcare waiti...        1   

              category                entrepreneurs      location  \
0            Novelties               Darrin Johnson  St. Paul, MN   
1       Specialty Food                   Tod Wilson  Somerset, NJ   
2  Baby and Child Care              Tiffany Krumins   Atlanta, GA   
3    Consumer Services  Nick Friedman, Omar Soliman     Tampa, FL   
4    Consumer Services               Kevin Flannery      Cary, NC   

                               website  askedFor  exchangeForStake  valuation  \
0                                  NaN   1000000                15    6

In [3]:
#What's up with NumPy? 
#What can do with NumPy
#What's the value it offers compared to plain Python? 
#Link to take a look to draw out points
#Efficiency in storage of data
#Efficiency in reshaping data
#Efficiency in performing Mathematical operations
'''NEED TO COME WITH A GOOD EXAMPLE HERE TO MAKE THE DATA SET MORE MEANINGFUL'''



#Note that in NumPy- all the elements in the array have to be of the same datatype


#In NumPy to form an arr

list_of_floats = [3.0,4.0,3.2,1.2,3.4,5.4,5.0,3.0,43.2,3.4]

#Forming an NumPy array from a list 

arr1 = np.array(list_of_floats, dtype='float') #dtype = 'float'/'int'/'str'

print(arr1)

print(type(arr1)) #Explain what an ndarray=> n dimensional array is. 


#Shape of this ndarray

print(arr1.shape) #10 ROWS, No columns #How to interpret this. 

#Suppose we want to reshape the array to have 5 rows and 2 columns. How can that be acheived? 

arr1.shape = (5,2)

print(arr1.shape)
print(arr1)

list2 = [3,4,4,3,2,2,4,2,3,2,2,1,0,7,6,5,4,3,3,2,2,2,2,1,2,4,5,2,2,2]

arr2 = np.array(list2,dtype='int')

print(arr2.shape)

# arr2.shape = (2,15)

arr2_reshaped1 = np.reshape(arr2,(2,15)) #The -1 feature in reshaping is super neat! 

#How does -1 work in NumPy. With -1 Python decides the -1 dimension 

#So np.reshape(arr2,(2,15)) and (arr2,(2,-1)) are equivalent 

print(arr2)
print(arr2_reshaped1)

# arr2_reshaped2 = np.reshape(arr2, (2,3,-1))

# print(arr2_reshaped2)






[ 3.   4.   3.2  1.2  3.4  5.4  5.   3.  43.2  3.4]
<class 'numpy.ndarray'>
(10,)
(5, 2)
[[ 3.   4. ]
 [ 3.2  1.2]
 [ 3.4  5.4]
 [ 5.   3. ]
 [43.2  3.4]]
(30,)
[3 4 4 3 2 2 4 2 3 2 2 1 0 7 6 5 4 3 3 2 2 2 2 1 2 4 5 2 2 2]
[[3 4 4 3 2 2 4 2 3 2 2 1 0 7 6]
 [5 4 3 3 2 2 2 2 1 2 4 5 2 2 2]]


In [4]:
#Part I: Basic Array Operations using NumPy

list_one = [1,2,3]

array_one = np.array(list_one) 



print(array_one[2])
print(array_one.size)


3
3


Approach could be. A little bit of NumPy and a lot more time for Pandas. How can I make the NumPy part (20mins) exciting? 

In [7]:
print (df['askedFor'].median())


150000.0


In [25]:
#START

#We we will be learning NumPy and Pandas
#At a high-level, what NumPy does? Allows for mathematical operations to performed on data quickly and conveniently
#What does Pandas today? 

#How are going to spend time today? Spend about 15-20 mins on NumPy. The syntax of NumPy comes in handy for other 
#Packages like Pandas because these packages are built on top of NumPy. 


#So why do we even need NumPy when we have lists 

#Suppose, we you run a large business for which we have three years of data. The data might be potentially stored
#in a list like below. 

rev_list = [300,350,450,550,320,340,440,580]


cost_list = [250,280,320,360,280,270,340,400]

#We run into a problem 

#Suppose, you want to calculate the profit. Which is Revenue - Costs. 

#We can't do the following

# profit_list = rev_list - cost_list 

#We could technically use a list comprehension 
# profit_list = [ rev-cost for rev,cost in zip(rev_list, cost_list)]
# print(profit_list) 
#But this is still inconvenient.
#This is where NumPy comes in handy. 

#So first we need to create a NumPy ARRAY!

rev_array = np.array(rev_list)

print(type(rev_array)) #So we are working with n-dimensional arrays 

cost_array = np.array(cost_list) 

profit_array = (rev_array - cost_array) #Profits

profit_percent_array = profit_array / rev_array *100


print(profit_percent_array) #This isn't a finance class. But this is called the profit margin. 


#Suppose you want to know the years in which the profit margin was greater than 20 %

print (profit_percent_array >20)

#So we get an array of boolean values

#We can print the specific values 

print(profit_percent_array[profit_percent_array > 20])


#Teach things like how to reshape data. Maybe have it has 4 quarters and have 2 years worth of data. 



<class 'numpy.ndarray'>
[16.66666667 20.         28.88888889 34.54545455 12.5        20.58823529
 22.72727273 31.03448276]
[False False  True  True False  True  True  True]
[28.88888889 34.54545455 20.58823529 22.72727273 31.03448276]
